name: Deploy ASP.NET Core Produtos-AWS to Elastic Beanstalk

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
  EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
  S3_BUCKET_DEPLOY: ${{ secrets.S3_BUCKET_DEPLOY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: |
          dotnet publish src/ProdutosAws.Web/ProdutosAws.Web.csproj \
            -c Release \
            -o published \
            --no-build

      - name: Verify publish folder
        run: |
          echo "===== PUBLISHED FILES ====="
          ls -la published

      - name: Create deployment zip
        run: |
          cd published
          zip -r ../deploy.zip .

      - name: Verify zip file
        run: |
          echo "===== ROOT FILES ====="
          ls -la

          echo "===== ZIP INFO ====="
          unzip -l deploy.zip | head -30

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Debug AWS Configuration
        run: |
          echo "===== AWS CONFIG ====="
          echo "REGION=${{ env.AWS_REGION }}"
          echo "APPLICATION=${{ env.EB_APPLICATION_NAME }}"
          echo "ENVIRONMENT=${{ env.EB_ENVIRONMENT_NAME }}"
          echo "BUCKET=${{ env.S3_BUCKET_DEPLOY }}"

          echo "===== AWS CALLER ====="
          aws sts get-caller-identity

      - name: Upload deploy package to S3
        run: |
          aws s3 cp deploy.zip s3://${{ env.S3_BUCKET_DEPLOY }}/deploy-${{ github.sha }}.zip

      - name: Verify uploaded package
        run: |
          echo "===== S3 FILES ====="
          aws s3 ls s3://${{ env.S3_BUCKET_DEPLOY }}/

      - name: List Elastic Beanstalk applications
        run: |
          echo "===== ELASTIC BEANSTALK APPLICATIONS ====="
          aws elasticbeanstalk describe-applications

      - name: Create Elastic Beanstalk application version
          run: |
            aws elasticbeanstalk create-application-version \
            --application-name "${{ env.EB_APPLICATION_NAME }}" \
            --version-label "v-${{ github.sha }}" \
            --source-bundle S3Bucket="${{ env.S3_BUCKET_DEPLOY }}",S3Key="deploy-${{ github.sha }}.zip" \
            --process

            - name: Wait for application version to be processed
              run: |
                VERSION="v-${{ github.sha }}"
                
                echo "Waiting for version $VERSION to become PROCESSED..."
                
                for i in {1..30}
                do
                  STATUS=$(aws elasticbeanstalk describe-application-versions \
                    --application-name "${{ env.EB_APPLICATION_NAME }}" \
                    --version-labels "$VERSION" \
                    --query "ApplicationVersions[0].Status" \
                    --output text)
                
                  echo "Current status: $STATUS"
                
                  if [ "$STATUS" = "PROCESSED" ]; then
                    echo "Application version processed successfully."
                    exit 0
                  fi
                
                  sleep 10
                done
                
                echo "Timeout waiting for application version processing."
                exit 1

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ env.EB_ENVIRONMENT_NAME }}" \
            --version-label "v-${{ github.sha }}"

      - name: Get environment status
        run: |
          echo "===== ENVIRONMENT STATUS ====="
          aws elasticbeanstalk describe-environments \
            --environment-names "${{ env.EB_ENVIRONMENT_NAME }}"